name: Build on pull request to main

on:
  pull_request:
    branches: [ main ]

jobs:
  build-workflow:
    uses: ./.github/workflows/build-workflow.yml
    with:
      ref-name: ${{ github.ref_name }}
    secrets: inherit
