
name: Build main

on:
  push:
    branches: [ 'main' ]

jobs:
  build-workflow:
    uses: ./.github/workflows/build-workflow.yml
    with:
      ref-name: ${{ github.ref_name }}
    secrets: inherit

  prepare-release-draft:
    needs: [ build-workflow ]
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/release-draft.yml
    secrets: inherit

  dependency-submission:
    needs: [ build-workflow,prepare-release-draft ]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
