name: Build main and pull requests

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v3

      - name: display env vars
        run: |
          echo dollar {2github.workspace}2 = ${{ github.workspace }}
          echo dollar GITHUB_WORKSPACE     = $GITHUB_WORKSPACE
          echo dollar {GITHUB_WORKSPACE}   = ${GITHUB_WORKSPACE}
          echo dollar {2GITHUB_WORKSPACE2} = ${{GITHUB_WORKSPACE}}
          echo dollar GITHUB_ENV           = $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      # using wrapper version (supposed to be 7.5.1)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Gradle clean
        uses: gradle/gradle-build-action@v2
        with:
          arguments:  --parallel  clean

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments:  --parallel  build
