name: Build main and pull requests

on:
  push:
    branches: [ "**" ]

  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      # using wrapper version (supposed to be 7.5.1)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: digma-otel-agent-extension-0.8.5
          path: ./agent-extension/build/libs/digma-otel-agent-extension-0.8.5.jar
          retention-days: 5
