
name: Publish

on:
  # Triggers the workflow on push of tags (release)
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      # using wrapper version (supposed to be 7.5.1)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true

      # setting version
      - name: update version in version.gradle.kts
        run: |
          ./scripts/update_version.sh ${{ steps.tag.outputs.tag }}

      # version is set, now can run gradle

      - name: Gradle clean
        uses: gradle/gradle-build-action@v2
        with:
          arguments:  --parallel  clean

      # make sure that "gradlew publish" runs in NO parallel mode, since it might create multiple repositories on the OSS server

      - name: Publish to OSSRH (using Gradle)
        uses: gradle/gradle-build-action@v2
        env:
          EV_ossrhUsername: asher-digma
          EV_ossrhPassword: ${{ secrets.DIGMA_ASHER_OSSRH_PASSWORD }}
        with:
          arguments: |
            --no-parallel
            publish
            -Psigning.secretKeyRingFile=${{ github.workspace }}/xtra/security/secr-key-ring-file-gpg.bin
            -Psigning.password=${{ secrets.DIGMA_GPG_SIGNING_PASSWORD }}
            -Psigning.keyId=${{ secrets.DIGMA_GPG_SIGNING_KEYID }}

      # artifacts are now published into OSSRH , you can browse https://s01.oss.sonatype.org/#stagingRepositories and search for Staging Repositories
      - name: Copy and Rename digma-otel-agent-extension
        run: |
            cp ./agent-extension/build/libs/digma-otel-agent-extension-${{ steps.tag.outputs.tag }}.jar ./agent-extension/build/libs/digma-otel-agent-extension.jar

      - name: Publish digma-otel-agent-extension
        uses: actions/upload-artifact@v3
        with:
          name: digma-otel-agent-extension
          path: ./agent-extension/build/libs/digma-otel-agent-extension.jar