
name: Publish

on:
  # Triggers the workflow on push of tags (release)
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true

      - name: update version in version.gradle.kts
        run: |
          ./scripts/update_version.sh ${{ steps.tag.outputs.tag }}
          cat version.gradle.kts

      - name: commit new version file
        uses: stefanzweifel/git-auto-commit-action@v4.14.0
        with:
          # Commit message
          commit_message: "bump version ${{ steps.tag.outputs.tag }}"

      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew build
